# -*- coding: utf-8 -*-
"""Stock Portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KAqKIZITryv1MbqM1hsnxsbHkDAboJK
"""

# -----------------------------------------
# ✅ CodeAlpha Internship - Task 1
# Stock Portfolio Tracker by Mariyam Younas
# -----------------------------------------

import csv  # for saving data in a .csv file

# Hardcoded dictionary of stock prices
stock_prices = {
    "AAPL": 180, "TSLA": 250, "GOOG": 130, "MSFT": 300, "AMZN": 140,
    "META": 320, "NFLX": 410, "NVDA": 450, "AMD": 120, "INTC": 35,
    "ORCL": 125, "IBM": 165, "ADBE": 550, "CRM": 240, "PYPL": 70,
    "UBER": 60, "LYFT": 12, "SHOP": 70, "DIS": 90, "SONY": 88,
    "BABA": 78, "T": 16, "VZ": 33, "PEP": 170, "KO": 58, "NKE": 98,
    "PFE": 34, "JNJ": 155, "WMT": 160, "COST": 540, "MCD": 280,
    "SBUX": 95, "BA": 195, "GE": 120, "XOM": 110, "CVX": 150
}

# Create an empty dictionary to store user's portfolio
portfolio = {}

print("📊 Welcome to the Stock Portfolio Tracker!\n")
print("Available Stocks:")
print(", ".join(stock_prices.keys()))
print("\n-------------------------------------")

# Ask user how many stocks they want to add
num_stocks = int(input("How many different stocks do you own? "))

# Take user input for each stock
for i in range(num_stocks):
    stock_name = input(f"\nEnter stock name #{i+1} (e.g., AAPL, TSLA): ").upper()
    quantity = int(input(f"Enter quantity of {stock_name}: "))

    # Check if stock is in our price list
    if stock_name in stock_prices:
        portfolio[stock_name] = quantity
    else:
        print(f"❌ {stock_name} not found in price list. Skipped.")

# Calculate total investment
total_investment = 0
print("\n-------------------------------------")
print("📈 Your Portfolio Summary:")
for stock, qty in portfolio.items():
    price = stock_prices[stock]
    total = price * qty
    print(f"{stock}: {qty} shares × ${price} = ${total}")
    total_investment += total

print("\n💰 Total Investment Value:", total_investment)
print("-------------------------------------")

# Optional: Save to CSV file
save = input("\nDo you want to save the result to a CSV file? (yes/no): ").lower()
if save == "yes":
    with open("portfolio.csv", mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Stock", "Quantity", "Price per Share ($)", "Total Value ($)"])
        for stock, qty in portfolio.items():
            writer.writerow([stock, qty, stock_prices[stock], stock_prices[stock] * qty])
        writer.writerow([])
        writer.writerow(["Total Investment", "", "", total_investment])
    print("✅ Portfolio saved to 'portfolio.csv' successfully!")

print("\nThank you for using the Stock Portfolio Tracker! 🚀")